sudo: required
language: scala

scala:
  - 2.12.4
  - 2.11.12

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

script:
  - cp /usr/bin/qemu-arm-static/
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt dockerBuildAndPush
